jmgilman/vaultrs

src/api.rs
src/api/sys/requests.rs
src/sys.rs

in order to unwrap said token without authenticating first.
From the `sys/wrapping/unwrap` api docs (https://www.vaultproject.io/api-docs/system/wrapping-unwrap#wrapping-unwrap):
> This endpoint can be used by using a wrapping token as the client token in the API call, in which case the token parameter is not required [...]. Do not use the wrapping token in both locations; this will cause the wrapping token to be revoked but the value to be unable to be looked up, as it will basically be a double-use of the token!
I have tested that it works. Should I add a test case to the cargo tests?

Adds support for using wrapping token as client token

---

src/client.rs

Apologies if I am fixing code that you did not intend to release yet; I am writing an application using this library and noticed the client login method does not take effect (requests to Vault are denied).

Fixes bug in generic login for clients

---

.github/workflows/audit.yml
Cargo.toml

Upgrading tracing-subscriber v0.2.17 -> v0.3.1
Upgrading tracing-test v0.1 -> v0.1.0
Upgrading serde v1.0.127 -> v1.0.130
Upgrading dockertest-server v0.1.3 -> v0.1.4
Upgrading serde_json v1.0.66 -> v1.0.68
Upgrading reqwest v0.11.4 -> v0.11.6
Upgrading http v0.2.4 -> v0.2.5
Upgrading bytes v1.0.1 -> v1.1.0
Upgrading thiserror v1.0.26 -> v1.0.30
Upgrading rustify_derive v0.5.0 -> v0.5.2
Upgrading tracing v0.1.27 -> v0.1.29
Upgrading rustify v0.5.0 -> v0.5.2

Upgrades cargo dependencies to latest versions

---

src/api/kv2/requests.rs
src/kv2.rs

this will fix #24 
the UrlQueryParseError when using kv2::read(),
by optionally sending the version param instead of using default
value of 0

make version optional, fixes #24

---

Cargo.toml

When trying to build a non-openssl linked binary I kept getting openssl pulled in as a dependency.
Turns out rustify has similar features scheme as reqwest, thus disabling default features and requiring only rustls-tls enables openssl-free binaries to be built.  I figured this would be an acceptable solution since vaultrs is already depending only on rustls-tls.

Change rustify dependency to require only rustls-tls

---

src/api/auth/oidc/requests.rs

When trying out JWT login into Vault I got errors on the vault server saying GET was not supported. Looking at the API docs and the source comments shows it should be a POST.
Changed the method to be POST and the code runs successfully now.

Fix HTTP Method in JWT login request to be a POST

---

src/client.rs
tests/client.rs

Hi, 
this is the PR attempting to solve #29
Let me know, if you'd like me to make any changes. The test file I've added is kept fairly simple...
Cheers,
R

Allow building VaultClientSettings without address

---

src/api/kv2/requests.rs
src/kv2.rs
tests/kv2.rs

This pull request adds support for vaults compare-and-swap feature. It is backwards compatible by adding the `kv2::set_with_options` function that includes an argument for `SetSecretRequestOptions`.
closes https://github.com/jmgilman/vaultrs/issues/33

feat: add support for cas option for kv2 backend

---

Cargo.toml
README.md

First, many thanks for your great library! As you know, `reqwest` allows to choose from two TLS implementations (`rustls` and `native-tls`); however, for some reason (why?), `vaultrs` is fixed to using `rustls`: https://github.com/jmgilman/vaultrs/blob/a4c20bba8afb5e63174472683859719470686d04/Cargo.toml#L24-L25
This PR allows to choose via a feature between `rustls` and `native-tls` to avoid having two crypto stacks in the same binary. In my example (a project already depending on `native-tls` due to other libraries), this saved ~900kB in the (stripped) release binary.
For backwards compatibility, the PR makes sure that `rustls` is still chosen as the default TLS implementation. In a version 0.7, this could probably be simplified.

Allow to choose between rustls and native-tls TLS implementations

---

Cargo.toml
README.md
src/api.rs
src/api/transit.rs
src/api/transit/requests.rs
src/api/transit/responses.rs
src/lib.rs
src/transit.rs
tests/transit.rs

Resolves #5 
This implements most of the transit secrets engine API, minus importing external keys or `batch_input` parameters (but would be easy enough to add on top).

feat: add support for transit secrets engine

---

src/api/pki/responses.rs

Allow identifying revoked certs.
The added field is actually present on the vault responses, an example:
```
vault read pki/cert/26:12:f5:e5:de:31:5d:29:b9:52:29:7d:1c:bb:b2:a4:dc:f8:5b:a7
{
"request_id": "42f959ca-6fcb-043a-14f6-2151129237a0",
"lease_id": "",
"lease_duration": 0,
"renewable": false,
"data": {
"certificate": "-----BEGIN CERTIFICATE-----\nMIIE6DCCA1Cg...\n-----END CERTIFICATE-----",
"revocation_time": 1649448637
},
"warnings": null
}
```
Thanks & sorry (:

Support revocation_time

---

src/api/kv2/requests.rs
src/api/kv2/responses.rs
tests/kv2.rs

Hello, this adds support for the [`custom_metadata` map in KV2](https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#read-secret-metadata).

KV2: add support for custom metadata

---

src/client.rs

Add support for client TLS certificates in order to authenticates client side connections.
It uses vault environment variables (as specified here: https://developer.hashicorp.com/vault/docs/commands) as default values.
Implementation is done for the rustls feature and still need to be implemented for native-tls.

Add support for client TLS

---

src/api.rs

Adds `X-Vault-Request: true` as a default header. Closes https://github.com/jmgilman/vaultrs/issues/66
:tulip:

Make X-Vault-Request a default header

---

src/api.rs
tests/kv2.rs

Fix URL-Encoding in Path applied twice

---

Cargo.toml

small change to enable the use of `native-tls-vendored` feature in `reqwest`
was having `openssl` issues and this was the only way i could build: https://github.com/seanmonstar/reqwest/issues/377

native tls vendored feature

---

README.md
src/api.rs
src/api/aws.rs
src/api/aws/requests.rs
src/api/aws/responses.rs
src/aws.rs
src/lib.rs
tests/aws.rs
tests/common.rs

Adds support for [AWS Secret Engine](https://developer.hashicorp.com/vault/docs/secrets/aws) with tests and docs
I tried to re-use existing code pattern and modules and tests, feel free to comment if it does not match somehow so code can be kept clean
Implementation is being used by a https://github.com/novadiscovery/novops branch, it works fine so far :)

feat: AWS Secret Engine

---

.github/workflows/ci.yml
Cargo.toml
src/api/auth.rs
src/api/auth/cert.rs
src/api/auth/cert/requests.rs
src/api/auth/cert/responses.rs
src/auth.rs
src/auth/cert.rs
tests/cert.rs
tests/vault_bind_mounts_container.rs

The first commit is cherry picked from #62 
The second one is specific to this PR and allow one to use [certificate to login to vault](https://developer.hashicorp.com/vault/docs/auth/cert).

Add support for login via certificate

---

src/api/sys/requests.rs
src/api/sys/responses.rs
src/sys.rs
tests/sys.rs
tests/vault_prod_container.rs

This add the `/sys/init` endpoint, which is useful to automate production Vault initialization.

add sys init endpoint

---

src/sys.rs

Currently the unseal key is logged when requesting `/sys/unseal` . This is problematic because even if the user  only  prints log to stdout, the unseal key could be written on the disk because of the swap mechanism. Besides, it's the users that configure their subscriber, so they could end up sending their unseal key to a remote log server without even noticing it. 
This PR prevents the unseal key from being logged. 
> Note: this might be worth checking out if other APIs don't also leak sensitive information.

prevent leaking unseal key

---

Cargo.toml

Bump reqwest to 0.12, unlocking the use of hyper 1.0 and rustls 0.22 
~~Waiting on https://github.com/jmgilman/rustify/pull/17~~

bump reqwest to 0.12

---

src/client.rs

I was trying to bump reqwest to version 0.12.x in my project.
However, I couldn't because the latest version of vaultrs uses version 0.11.x so I was not able to build an `Identity`:
```
error[E0308]: mismatched types
|
90 |             identity,
|             ^^^^^^^^ expected `reqwest::tls::Identity`, found `reqwest::Identity`
|
= note: `reqwest::Identity` and `reqwest::tls::Identity` have similar names, but are actually distinct types
note: `reqwest::Identity` is defined in crate `reqwest`
--> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.2/src/tls.rs:77:1
|
77 | pub struct Identity {
| ^^^^^^^^^^^^^^^^^^^
note: `reqwest::tls::Identity` is defined in crate `reqwest`
--> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.27/src/tls.rs:75:1
|
75 | …
```

Re-export identity to allow users to use a different version of reqwest

---

src/api.rs
src/auth/approle.rs
src/auth/aws.rs
src/auth/cert.rs
src/auth/kubernetes.rs
src/auth/oidc.rs
src/auth/userpass.rs
src/aws.rs
src/database.rs
src/identity/entity.rs
src/identity/entity_alias.rs
src/identity/group.rs
src/identity/group_alias.rs
src/kv1.rs
src/kv2.rs
src/pki.rs
src/ssh.rs
src/sys.rs
src/token.rs
src/transit.rs
vaultrs-login/src/method.rs

Attempt to address some of the concerns raised in https://github.com/jmgilman/vaultrs/issues/86
- add the HTTP verb to the log to differentiate which endpoint is actually used
- use structured logging, so it will be easier to process the log afterward. For instance, structured logging allows data  to be a key value inside a json  
- move the span from the top-level function to the inner wrapper, so we don't get to see the parameters. Parameters can contain sensitive information (https://github.com/jmgilman/vaultrs/pull/85) and tends to bloat the logs. Users can still log the parameter if they want by adding a trace themself.
- remove some info traces that were redundant or did not contains useful information
Here there is an example to the new log, which can be useful to compare with the …

Improve logging

---

src/api/sys/requests.rs
src/api/sys/responses.rs
src/sys.rs
tests/sys.rs

add: 
- get configuration of the secret engine
- disable mount

Complete the mount endpoint

---

Cargo.toml
src/api/transit.rs
src/api/transit/responses.rs
tests/transit.rs

As described in #93 the current implementation fails to deserialize a read transit engine key response if the key is asymmetric. The asymmetric response differs as it includes the public key inside of the keys field:
```
// vault@926ee8c21172:/$ curl -XGET --insecure --silent -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/transit/keys/my-new-key
{
"request_id": "b59d5612-b16f-8742-641c-32e29943433f",
"lease_id": "",
"renewable": false,
"lease_duration": 0,
"data": {
"allow_plaintext_backup": false,
"auto_rotate_period": 0,
"deletion_allowed": false,
"derived": false,
"exportable": false,
"imported_key": false,
"keys": {
"1": {
"creation_time": "2024-05-10T13:36:49.809157592Z",
"name": "rsa-2048",
"public_key": "-----BEGIN PUBLIC …
```

#93 Add support for asymmetric keys to vault transit engine

---

src/api.rs
src/client.rs

IMO these should be debug-level logs, not informational ones.

Improve logging message levels to reduce verbosity

---

vaultrs-tests/tests/api_tests/sys.rs

When I want to manually inspect the vault state after a test, I add a `std::mem::ManuallyDrop` to prevent `Drop` from running and cleaning the Vault. Sadly this one got committed into master.

Fix: remove manually drop from test

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/api.rs
src/api/sys/requests.rs
src/kv1.rs
src/lib.rs
vaultrs-login/src/lib.rs
vaultrs-tests/tests/api_tests/approle.rs
vaultrs-tests/tests/api_tests/aws.rs
vaultrs-tests/tests/api_tests/cert.rs
vaultrs-tests/tests/api_tests/database.rs
vaultrs-tests/tests/api_tests/identity.rs
vaultrs-tests/tests/api_tests/kubernetes.rs
vaultrs-tests/tests/api_tests/kv2.rs
vaultrs-tests/tests/api_tests/login.rs
vaultrs-tests/tests/api_tests/oidc.rs
vaultrs-tests/tests/api_tests/pki.rs
vaultrs-tests/tests/api_tests/ssh.rs
vaultrs-tests/tests/api_tests/sys.rs
vaultrs-tests/tests/api_tests/token.rs
vaultrs-tests/tests/api_tests/transit.rs
vaultrs-tests/tests/api_tests/userpass.rs

Cleanup the further the testsuite by doing the following:
- Remove `assert!(result.is_ok())` pattern, which gives less context in case of failure than `result.unwrap()`
- Move the example of the README directly inside the `lib.rs` to compile them. Fix some examples that silently didn't compile until then.
- Fix doc generation warning and add a ci check for it
- Detect slow test with `cargo +nightly t --workspace -- -Z unstable-options --report-time --format json 2> /dev/null | jq` and ignore them locally. This improves the developer experience.
- Update README to new test location since `testscontainers` migration
I split the PR into several commits to ease the review.

Cleanup testsuite

---

src/api/pki/requests.rs

This PR add missing parameters to the generate intermediate CSR: https://developer.hashicorp.com/vault/api-docs/secret/pki#generate-intermediate-csr

Add missing parameters to the generate intermediate request

---

src/api/pki/responses.rs

Add `expiration` to `SignCertificateResponse` that wasn't parsed until then

add `expiration` to `SignCertificateResponse`

---

CHANGELOG.md
README.md
src/api.rs
src/api/cubbyhole.rs
src/api/cubbyhole/requests.rs
src/api/cubbyhole/responses.rs
src/api/kv1/requests.rs
src/cubbyhole.rs
src/kv1.rs
src/lib.rs
vaultrs-tests/tests/api_tests/cubbyhole.rs
vaultrs-tests/tests/api_tests/identity.rs
vaultrs-tests/tests/api_tests/kv1.rs
vaultrs-tests/tests/api_tests/main.rs

Add support for the cubbyhole secret engine. It is functionally equivalent to KV1, so the code is practically the same. I was considering a non-inlined re-export of the kv1 engine but could not get that working with new doc comments to reflect the fact it is for the cubbyhole - if there is a way to do this that may be better for maintainability.
Closes #6.

Add support for cubbyhole

---

src/api/token/responses.rs

The [Lookup a token documentation](https://developer.hashicorp.com/vault/api-docs/auth/token#lookup-a-token-accessor) does not mention the `"role"` member, but it is returned for tokens that were created with a `role_name`. 
Tested with Vault `1.19.3`.

fix: add optional `role` member to `LookupTokenResponse`

---

src/api/sys/requests.rs
src/api/sys/responses.rs

The health endpoint returns non-200-status-codes WITH the `ReadHealthResponse` together, but `vaultrs` is just seeing the non-200 statuscode and throws an error. ignoring the actual content. As a workaround one can specify the return numbers that **vault** should send in certain situations.
Additionally the ReadHealthResponse no longer seemed to hold up with a `1.19` version of vault. So i updated it based on the go source code

workaround for #137 in /sys/health

---

src/api/pki/requests.rs

This MR correct the type of the `max_ttl` and `ttl` parameter from integer to string, corresponding to what expect the *vault* API

fix TTL type of create pki role
